name: deploy-docs

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# Build the docs and publish to gh-pages
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the jupyter-book
      uses: addnab/docker-run-action@v3
      with: 
          image: craigwillis/jupyter-book:latest
          options: -v ${{ github.workspace }}:/src
          run: jupyter-book build --all .
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
